#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# first homebrew installer
sh -c "./homebrew/install.sh"

# the all other installers
find . -name 'install.sh' -not -path "./homebrew/*" | while read installer ; do sh -c "${installer}" ; done
