# overrides some default settings of Mac OS X
# -------------------------------------------

# Turn off fade + popup animation effects
defaults write -g NSAutomaticWindowAnimationsEnabled -bool false

# Stop save and print dialogs from sliding out and down from the title bar
defaults write -g NSWindowResizeTime -float 0.01

# Make the click-sensitive surface of the resizing-button in the bottom right of windows bigger
defaults write -g AppleEdgeResizeExteriorSize 10

# Fix ugly fonts on external displays
defaults -currentHost write -g AppleFontSmoothing -int 2

# Set a blazingly fast keyboard repeat rate
defaults write -g KeyRepeat -int 0
defaults write -g InitialKeyRepeat -int 25

# Disable auto-correct
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false

# Turn on key repeat
defaults write -g ApplePressAndHoldEnabled -bool false

# Always see expanded save dialogs
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g PMPrintingExpandedStateForPrint -bool true

# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write -g AppleKeyboardUIMode -int 3

# Disable downloaded file 'quarantining' (that annoying "this app was downloaded from the internet" dialog)
defaults write com.apple.launchservices LSQuarantine -bool false

# Disable writing of .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Turn off rubberbanding
defaults write -g NSScrollViewRubberbanding -int 0

# don't set iCloud as default location
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# dock
# -------------------------------------------

# Disable 3D Dock
defaults write com.apple.dock no-glass -bool true

# Disable Dock magnification
defaults write com.apple.dock magnification -bool false

# make hidden applications transparent
defaults write com.apple.dock showhidden -bool YES

# Use the scale animation instead of genie for minimizing windows
defaults write com.apple.dock mineffect -string scale

# Turn off Mission Control zoom effects
defaults write com.apple.dock expose-animation-duration -int 0

# Make Launchpad show/hide instantly
defaults write com.apple.dock springboard-show-duration -int 0
defaults write com.apple.dock springboard-hide-duration -int 0

# Disable background blur in Launchpad
defaults write com.apple.dock springboard-blur-radius -int 150

# Enable mouse-over trigger for Dock stacks
defaults write com.apple.dock mouse-over-hilite-stack -bool true

# Set the size of the dock to 40
defaults write com.apple.dock tilesize -int 40

# Lock the Dock in size and position
defaults write com.apple.dock size-immutable -bool yes
defaults write com.apple.dock position-immutable -bool yes

# dashboard
# -------------------------------------------

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# finder
# -------------------------------------------

# Enables you to select and copy text in Quick Look windows
defaults write com.apple.finder QLEnableTextSelection -bool true

# Display full path to active directory in Finder
defaults write com.apple.finder PathBarRootAtHome -bool true

# Use Finder's column view as the default view mode
defaults write com.apple.finder FXPreferredViewStyle clmv

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Use AirDrop over every interface. srsly this should be a default.
defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1

# Show the ~/Library folder.
chflags nohidden ~/Library

# screencapture
# -------------------------------------------

# Let Screen Capture save in JPG format instead of PNG
defaults write com.apple.screencapture type -string jpg

# Disable shadow effect generated by Screen Capture
defaults write com.apple.screencapture disable-shadow -bool true

# Save screenshots in a dir
mkdir -p ~/Desktop/screenshots
defaults write com.apple.screencapture location ~/Desktop/screenshots

# battery
# -------------------------------------------

# Show remaining battery time; hide percentage
defaults write com.apple.menuextra.battery ShowPercent -string "NO"
defaults write com.apple.menuextra.battery ShowTime -string "YES"

# screensaver
# -------------------------------------------

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# trackpad
# -------------------------------------------

# Enable tap to click (Trackpad)
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

# terminal
# -------------------------------------------

# Only use UTF-8 in Terminal.app
defaults write com.apple.terminal StringEncodings -array 4

# iTunes
# -------------------------------------------

# Disable the Ping sidebar in iTunes
defaults write com.apple.iTunes disablePingSidebar -bool true

# Safari
# -------------------------------------------

# Set up Safari for development.
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" -bool true
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true


# Kill affected applications
for app in Safari Finder Dock Mail SystemUIServer; do killall "$app" >/dev/null 2>&1; done
